name: ttyd
on:
  workflow_dispatch:
  push:
    paths: .github/workflows/code-server.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2.2.0
        with:
          version: 0.13.0
          cache: true

      - name: Prepare environment
        run: |
          curl -Lk https://github.com/cloudflare/cloudflared/releases/download/2024.8.2/cloudflared-fips-linux-amd64 > cloudflared
          chmod +x cloudflared
          sudo mv cloudflared /usr/local/bin
          cloudflared --version

          curl -Lk "https://code.visualstudio.com/sha/download?build=stable&os=cli-alpine-x64" | gzip -d | tar -x
          sudo mv code /usr/local/bin

      - name: Start code server
        run: |
          code serve-web --host ::0 --without-connection-token &
          cloudflared tunnel --url localhost:8000
