name: Test
run-name: "Test: ${{github.event.head_commit.message}}"
on:
  workflow_dispatch:
  push:
    paths: .github/workflows/code-server.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout llvm-project
        uses: actions/checkout@v4.1.1

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2.2.0
        with:
          version: 0.13.0
          cache: true

      - name: Setup vscode server
        run: |
          # curl -Lk https://code.visualstudio.com/sha/download?build=stable&os=cli-alpine-x64 | gzip -d | tar -C /opt -xv
          # bore local 5000 --to bore.pub
          curl -Lk https://github.com/tsl0922/ttyd/releases/download/1.7.7/ttyd.x86_64 > ttyd
          chmod +x ttyd
          ./ttyd bash -l &
          # curl https://github.com/ekzhang/bore/releases/download/v0.5.1/bore-v0.5.1-x86_64-unknown-linux-musl.tar.gz | gzip -d | tar -C /opt -xv
          # /opt/bore local 5000 --to bore.pub

      - name: Run sshx
        run: |
          curl -sSf https://sshx.io/get | sh -s run

      - name: Debugging with tmate
        uses: mxschmitt/action-tmate@v3.18
