name: Run VS Code Server
on:
  workflow_dispatch:
  push:
    paths: .github/workflows/code-server.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.1

      - uses: zongou/run-vscode-server@0.0.3
        name: Run VS Code server to debug
        # if: ${{ failure() }}
