name: Run VS Code Server
on:
  workflow_dispatch:
  # push:
  #   paths: .github/workflows/code-server.yaml
    inputs:
      freespace:
        description: 'Free disk space'
        required: true
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Free Disk Space (Ubuntu)
        if: ${{ inputs.freespace }}
        uses: jlumbroso/free-disk-space@v1.3.1

      - name: Setup zig
        uses: goto-bus-stop/setup-zig@v2.2.0
        with:
          version: 0.14.0
          cache: true

      - uses: zongou/run-vscode-server@0.0.3
        name: Run VS Code server to debug
        # if: ${{ failure() }}
