name: code-server
on:
  workflow_dispatch:
  push:
    paths: .github/workflows/code-server.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Get Latest Release
        id: get_latest_release
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const { data } = await octokit.rest.repos.getLatestRelease({
              owner: "cloudflare",
              repo: "cloudflared"
            });
            console.log(`Latest release tag: ${data.tag_name}`);
            return data.assets[0].browser_download_url; // Assuming the first asset is the one you want

      - name: Print Download URL
        run: echo ${{ steps.get_latest_release.outputs.result }}

      - name: Prepare environment
        run: |
          curl -Lk https://github.com/cloudflare/cloudflared/releases/download/2024.9.1/cloudflared-fips-linux-amd64 > cloudflared
          chmod +x cloudflared
          sudo mv cloudflared /usr/local/bin
          cloudflared --version

          curl -Lk "https://update.code.visualstudio.com/latest/cli-alpine-x64/stable" | gzip -d | tar -x
          sudo mv code /usr/local/bin

      - name: Start code-server
        run: |
          curl -Lk https://github.com/mvdan/sh/releases/download/v3.9.0/shfmt_v3.9.0_linux_amd64 > shfmt
          chmod +x shfmt
          sudo mv shfmt /usr/local/bin
          shfmt --version

          code serve-web --host ::0 --without-connection-token &
          cloudflared tunnel --url localhost:8000
