# Build and find out which commit breaks


# https://github.com/microsoft/vscode/wiki/How-to-Contribute
name: Find broken commit
run-name: Find broken commit
on:
  workflow_dispatch:
    inputs:
      from:
        description: "from"
        required: true
      depth:
        description: "depth"
        default: "1000"
        required: true
        type: number

jobs:
    get-random-commits:
        runs-on: ubuntu-latest
        outputs:
          commits: ${{ steps.get_commits.outputs.commits }}
        steps:
          - name: Checkout repository
            uses: actions/checkout@v2
    
          - name: Get 10 random commit IDs
            id: get_commits
            run: |
              echo commits=$(git log -n${{inputs.depth}} --foramt="%H" | awk 'NR % 100==0')>> $GITHUB_OUTPUT
    
    reset-to-commit:
        needs: get-random-commits
        runs-on: ubuntu-latest
        strategy:
          matrix:
            commit: ${{ needs.get-random-commits.outputs.commits }}
        steps:
          - name: Reset to commit
            run: |
                # git reset --hard ${{ matrix.commit }}
                echo "Reset to commit: ${{ matrix.commit }}"
