# Build and find out which commit breaks


# https://github.com/microsoft/vscode/wiki/How-to-Contribute
name: Find vscode broken commit
on:
  push:
    paths:
      - ".github/workflows/find_vscode_broken_commit.yaml"
  workflow_dispatch:
    inputs:
      from:
        description: "from"
        default: "HEAD"
        required: true
      depth:
        description: "depth"
        default: "1000"
        required: true
        type: number

jobs:
    get-random-commits:
        runs-on: ubuntu-latest
        outputs:
          commits: ${{ steps.get_commits.outputs.commits }}
        steps:
          - name: Checkout repository
            uses: actions/checkout@v2
            with:
              fetch-depth: ${{inputs.depth||'1000'}}
    
          - name: Get 10 random commit IDs
            id: get_commits
            run: |
              echo "commits=$(git log -n1000 --format="%H" | awk 'NR % 100==0' | jq -R -s -c 'split("\n") | map(select(length > 0))')">> $GITHUB_OUTPUT

          - name: Test output
            run: |
              echo ${{steps.get_commits.outputs.commits}}

    reset-to-commit:
        needs: get-random-commits
        runs-on: ubuntu-latest
        strategy:
          matrix:
            commit: ${{needs.get-random-commits.outputs.commits}}
        steps:
          - name: Reset to commit
            run: |
                # git reset --hard ${{ matrix.commit }}
                echo "Reset to commit: ${{ matrix.commit }}"
