# Build and find out which commit breaks


# https://github.com/microsoft/vscode/wiki/How-to-Contribute
name: Find vscode broken commit
on:
  push:
    paths:
      - ".github/workflows/find_vscode_broken_commit.yaml"
  workflow_dispatch:
    inputs:
      from:
        description: "from"
        default: "HEAD"
        required: true
      depth:
        description: "depth"
        default: 1000
        required: true
        type: number

permissions:
  contents: write
  actions: write

jobs:
    get-commits:
        runs-on: ubuntu-latest
        outputs:
          commits: ${{steps.get_commits.outputs.commits}}
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4
            with:
              repository: microsoft/vscode
              fetch-depth: ${{inputs.depth||1000}}
    
          - name: Get commits
            id: get_commits
            run: |
              echo "commits=$(git log -n${{inputs.depth||1000}} --format="%H" | awk 'NR % 100==0' | jq -R -s -c 'split("\n") | map(select(length > 0))')">> $GITHUB_OUTPUT

          - name: Test
            run: |
              echo ${{inputs.depth}}
              echo ${{inputs.depth.default}}
              echo ${{inputs.depth||inputs.depth.default}}
              echo ${{steps.get_commits.outputs.commits}}

          - name: Delete workflow runs
            uses: Mattraks/delete-workflow-runs@v2.0.6
            with:
              delete_workflow_pattern: "Find vscode broken commit"
              retain_days: 0
              keep_minimum_runs: 1

    build:
        needs: get-commits
        runs-on: ubuntu-latest
        strategy:
          matrix:
            commit: ${{fromJson(needs.get-commits.outputs.commits)}}
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4
            with:
              repository: microsoft/vscode
              ref: ${{matrix.commit}}

          - name: Build
            run: |
              npm install
              npm run gulp "${task}"