name: Caching Primes
run-name: "Caching Primes: ${{github.event.head_commit.message}}"
on:
  workflow_dispatch:
  push:
    paths: .github/workflows/new_cache_example.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Restore cached Primes
      id: cache-primes-restore
      uses: actions/cache/restore@v4
      with:
        path: |
          filea
          fileb
        key: ${{ runner.os }}-primes
    
    - name: Create Primes if Restoring cache missed
      id: cache-primes-create
      if: steps.cache-primes-restore.outputs.cache-hit != 'true'
      run: |
        echo "Hello" > filea
        echo "World" > fileb
    
    - name: Save Primes
      id: cache-primes-save
      uses: actions/cache/save@v4
      with:
        path: |
          path/to/dependencies
          some/other/dependencies
        key: ${{ steps.cache-primes-restore.outputs.cache-primary-key }}

    - name: Print Primes
      run: |
        cat filea fileb