name: Test
run-name: "Test: ${{github.event.head_commit.message}}"
on:
  workflow_dispatch:
  push:
    paths: .github/workflows/test.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      # - name: Prepare environment
      #   run: |
      #     cat <<EOF >d
      #     export CHARSET=\${CHARSET:-UTF-8}
      #     export LANG=\${LANG:-C.UTF-8}
      #     export LC_COLLATE=\${LC_COLLATE:-C}
      #     export TERM=xterm-256color
      #     export COLORTERM=truecolor
      #     EOF

      #     sudo mv d /etc/profile.d/my_profile.sh

      #     sudo apt update

      #     helix_vesion=24.07
      #     helix_url=https://github.com/helix-editor/helix/releases/download/${helix_vesion}/helix-${helix_vesion}-x86_64-linux.tar.xz
      #     curl -L ${helix_url} | xz -d | tar -C /opt -x
      #     ln -snf /opt/helix-${helix_vesion}-x86_64-linux/hx /usr/local/bin/hx
      #     hx --version

      #     dufs_version=0.41.0
      #     dufs_url=https://github.com/sigoden/dufs/releases/download/v0.41.0/dufs-v0.41.0-x86_64-unknown-linux-musl.tar.gz
      #     curl -L ${dufs_url} | gzip -d | tar -C /usr/local/bin -x
      #     dufs --version

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2.2.0
        with:
          version: 0.13.0
          cache: true

      - name: Build host
        run: |
          git clone https://github.com/llvm/llvm-project --branch=llvmorg-18.1.8 --depth=1
          cd llvm-project
          mkdir -p "${BUILD_DIR}/llvm-host"
          cmake -S "$ROOTDIR/llvm" -B "${BUILD_DIR}/llvm-host" \
            -DCMAKE_INSTALL_PREFIX="${OUTPUT_DIR}/host" \
            -DCMAKE_PREFIX_PATH="${OUTPUT_DIR}/host" \
            -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_ENABLE_PROJECTS="lld;clang" \
            -DLLVM_ENABLE_LIBXML2=OFF \
            -DLLVM_ENABLE_ZSTD=OFF \
            -DLLVM_INCLUDE_UTILS=OFF \
            -DLLVM_INCLUDE_TESTS=OFF \
            -DLLVM_INCLUDE_EXAMPLES=OFF \
            -DLLVM_INCLUDE_BENCHMARKS=OFF \
            -DLLVM_INCLUDE_DOCS=OFF \
            -DLLVM_ENABLE_BINDINGS=OFF \
            -DLLVM_ENABLE_OCAMLDOC=OFF \
            -DLLVM_ENABLE_Z3_SOLVER=OFF \
            -DLLVM_TOOL_LLVM_LTO2_BUILD=OFF \
            -DLLVM_TOOL_LLVM_LTO_BUILD=OFF \
            -DLLVM_TOOL_LTO_BUILD=OFF \
            -DLLVM_TOOL_REMARKS_SHLIB_BUILD=OFF \
            -DCLANG_BUILD_TOOLS=OFF \
            -DCLANG_INCLUDE_DOCS=OFF \
            -DCLANG_TOOL_CLANG_IMPORT_TEST_BUILD=OFF \
            -DCLANG_TOOL_CLANG_LINKER_WRAPPER_BUILD=OFF \
            -DCLANG_TOOL_C_INDEX_TEST_BUILD=OFF \
            -DCLANG_TOOL_ARCMT_TEST_BUILD=OFF \
            -DCLANG_TOOL_C_ARCMT_TEST_BUILD=OFF \
            -DCLANG_TOOL_LIBCLANG_BUILD=OFF
          cmake --build "${BUILD_DIR}/llvm-host" --target llvm-tblgen clang-tblgen || true

      - name: Debugging with tmate
        uses: mxschmitt/action-tmate@v3.18
