name: Test
run-name: "Test: ${{github.event.head_commit.message}}"
on:
  workflow_dispatch:
  push:
    paths: .github/workflows/test.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # - uses: actions/checkout@v4

      - name: Restore host LLVM and Zig
        id: cache-restore-host_zig
        uses: actions/cache/restore@v4
        with:
          path: |
            out
          key: build_zig-Linux-0.13.0-host

      - name: Cache host LLVM and Zig
        if: steps.cache-restore-host_zig.outputs.cache-hit == 'true'
        uses: actions/cache/save@v4
        with:
          path: |
            out
          key: build_zig-0.13.0-host