name: Test
run-name: "Test: ${{github.event.head_commit.message}}"
on:
  workflow_dispatch:
  push:
    paths:
     .github/workflows/test.yaml

jobs:
  # container-job:
  #   runs-on: ubuntu-latest
  #   container: arm64/node:20.14.0-alpine
  #   steps:
  #       - run: node --version
  #       - run: npm --version
        
  test-job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Prepare
        run: |
          sudo apt install binfmt-support qemu-user-static
          
      - name: Run
        run: |

          # docker run --rm node:20.14.0-alpine /bin/sh -c 'uname -m' || true
          # echo ================================================================
          # docker run --rm arm64v8/node:20.11.1-alpine /bin/sh -c 'uname -m' || true
          # echo ================================================================
          # docker run --rm arm64/node:20.11.1-alpine /bin/sh -c 'uname -m' || true
          # echo ================================================================
          # docker run --platform linux/arm64 node:20.14.0-alpine /bin/sh -c 'uname -m' || true
          # echo ================================================================
          # docker run --platform linux/arm64 arm64/node:20.14.0-alpine /bin/sh -c 'uname -m' || true
          # echo ================================================================
          # docker run --platform linux/arm64 arm64v8/node:20.14.0-alpine /bin/sh -c 'uname -m' || true

          docker run --platform linux/arm64 node:20.14.0-alpine /bin/sh -c 'uname -m' || true
          docker run --platform arm64 node:20.14.0-alpine /bin/sh -c 'uname -m' || true
          

