name: Test
run-name: Build llvm ${{github.event.inputs.tag}}
on:
  workflow_dispatch:
  push:
    paths:
     .github/workflows/test.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Test
        run: |
          docker run --rm arm64:20.14.0-alpine /bin/sh -c 'node --version'
          

