name: Test
run-name: "Test: ${{github.event.head_commit.message}}"
on:
  workflow_dispatch:
  push:
    paths: .github/workflows/test.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      # - name: Prepare environment
      #   run: |
      #     cat <<EOF >d
      #     export CHARSET=\${CHARSET:-UTF-8}
      #     export LANG=\${LANG:-C.UTF-8}
      #     export LC_COLLATE=\${LC_COLLATE:-C}
      #     export TERM=xterm-256color
      #     export COLORTERM=truecolor
      #     EOF

      #     sudo mv d /etc/profile.d/my_profile.sh

      #     sudo apt update

      #     helix_vesion=24.07
      #     helix_url=https://github.com/helix-editor/helix/releases/download/${helix_vesion}/helix-${helix_vesion}-x86_64-linux.tar.xz
      #     curl -L ${helix_url} | xz -d | tar -C /opt -x
      #     ln -snf /opt/helix-${helix_vesion}-x86_64-linux/hx /usr/local/bin/hx
      #     hx --version

      #     dufs_version=0.41.0
      #     dufs_url=https://github.com/sigoden/dufs/releases/download/v0.41.0/dufs-v0.41.0-x86_64-unknown-linux-musl.tar.gz
      #     curl -L ${dufs_url} | gzip -d | tar -C /usr/local/bin -x
      #     dufs --version

      # - name: Debugging with tmate
      #   uses: mxschmitt/action-tmate@v3.18

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2.2.0
        with:
          version: 0.13.0
          cache: true

      - name: Build zlib and zstd
        env:
          ROOTDIR: ${{github.workspace}}
          TARGET: aarch64-linux-musl
          MCPU: baseline
        run: |
          zlib_version=1.3.1
          curl https://github.com/madler/zlib/releases/download/v${zlib_version/zlib-${zlib_version}.tar.xz -LkSs | xz -d | tar -x

          mv zlib-${zlib_version} zlib
          cd zlib
          cmake -S "$ROOTDIR/zlib" \
            -DCMAKE_INSTALL_PREFIX="$ROOTDIR/out/$TARGET-$MCPU" \
            -DCMAKE_PREFIX_PATH="$ROOTDIR/out/$TARGET-$MCPU" \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_CROSSCOMPILING=True \
            -DCMAKE_SYSTEM_NAME="$TARGET_OS_CMAKE" \
            -DCMAKE_C_COMPILER="zig;cc;-fno-sanitize=all;-s;-target;$TARGET;-mcpu=$MCPU" \
            -DCMAKE_CXX_COMPILER="zig;c++;-fno-sanitize=all;-s;-target;$TARGET;-mcpu=$MCPU" \
            -DCMAKE_ASM_COMPILER="zig;cc;-fno-sanitize=all;-s;-target;$TARGET;-mcpu=$MCPU" \
            -DCMAKE_RC_COMPILER="$ROOTDIR/out/host/bin/llvm-rc" \
            -DCMAKE_AR="$ROOTDIR/out/host/bin/llvm-ar" \
            -DCMAKE_RANLIB="$ROOTDIR/out/host/bin/llvm-ranlib"
          cmake --build . --target install

          curl https://github.com/facebook/zstd/releases/download/v1.5.6/zstd-1.5.6.tar.gz | gzip -d | tar -x
          mv zstd-1.5.6 zstd

          cp "$ROOTDIR/zstd/lib/zstd.h" "$ROOTDIR/out/$TARGET-$MCPU/include/zstd.h"
          cd "$ROOTDIR/out/$TARGET-$MCPU/lib"
          zig build-lib \
            --name zstd \
            -target $TARGET \
            -mcpu=$MCPU \
            -fstrip -OReleaseFast \
            -lc \
            "$ROOTDIR/zstd/lib/decompress/zstd_ddict.c" \
            "$ROOTDIR/zstd/lib/decompress/zstd_decompress.c" \
            "$ROOTDIR/zstd/lib/decompress/huf_decompress.c" \
            "$ROOTDIR/zstd/lib/decompress/huf_decompress_amd64.S" \
            "$ROOTDIR/zstd/lib/decompress/zstd_decompress_block.c" \
            "$ROOTDIR/zstd/lib/compress/zstdmt_compress.c" \
            "$ROOTDIR/zstd/lib/compress/zstd_opt.c" \
            "$ROOTDIR/zstd/lib/compress/hist.c" \
            "$ROOTDIR/zstd/lib/compress/zstd_ldm.c" \
            "$ROOTDIR/zstd/lib/compress/zstd_fast.c" \
            "$ROOTDIR/zstd/lib/compress/zstd_compress_literals.c" \
            "$ROOTDIR/zstd/lib/compress/zstd_double_fast.c" \
            "$ROOTDIR/zstd/lib/compress/huf_compress.c" \
            "$ROOTDIR/zstd/lib/compress/fse_compress.c" \
            "$ROOTDIR/zstd/lib/compress/zstd_lazy.c" \
            "$ROOTDIR/zstd/lib/compress/zstd_compress.c" \
            "$ROOTDIR/zstd/lib/compress/zstd_compress_sequences.c" \
            "$ROOTDIR/zstd/lib/compress/zstd_compress_superblock.c" \
            "$ROOTDIR/zstd/lib/deprecated/zbuff_compress.c" \
            "$ROOTDIR/zstd/lib/deprecated/zbuff_decompress.c" \
            "$ROOTDIR/zstd/lib/deprecated/zbuff_common.c" \
            "$ROOTDIR/zstd/lib/common/entropy_common.c" \
            "$ROOTDIR/zstd/lib/common/pool.c" \
            "$ROOTDIR/zstd/lib/common/threading.c" \
            "$ROOTDIR/zstd/lib/common/zstd_common.c" \
            "$ROOTDIR/zstd/lib/common/xxhash.c" \
            "$ROOTDIR/zstd/lib/common/debug.c" \
            "$ROOTDIR/zstd/lib/common/fse_decompress.c" \
            "$ROOTDIR/zstd/lib/common/error_private.c" \
            "$ROOTDIR/zstd/lib/dictBuilder/zdict.c" \
            "$ROOTDIR/zstd/lib/dictBuilder/divsufsort.c" \
            "$ROOTDIR/zstd/lib/dictBuilder/fastcover.c" \
            "$ROOTDIR/zstd/lib/dictBuilder/cover.c"

          tree $ROOTDIR/out/$TARGET-$MCPU/lib
