name: Test
run-name: "Test: ${{github.event.head_commit.message}}"
on:
  workflow_dispatch:
  push:
    paths: .github/workflows/test.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # - uses: actions/checkout@v4

      - name: Setup LLVM
        uses: ZhongRuoyu/setup-llvm@v0.1.1
        with:
          llvm-version: 18
    
      - name: find llvm-config
        run: |
          llvm-config --version
          clang --version
          lld --version || ld.lld --version

