name: Test
run-name: "Test: ${{github.event.inputs.tag}}"
on:
  workflow_dispatch:
  push:
    paths:
     .github/workflows/test.yaml

jobs:
  # container-job:
  #   runs-on: ubuntu-latest
  #   container: arm64/node:20.14.0-alpine
  #   steps:
  #       - run: node --version
  #       - run: npm --version
        
  test-job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Test
        run: |
          # docker pull node:20.14.0-alpine
          docker run --rm node:20.14.0-alpine /bin/sh -c 'node --version'
          

