name: Test
run-name: "Test: ${{github.event.head_commit.message}}"
on:
  workflow_dispatch:
  push:
    paths:
     .github/workflows/test.yaml

jobs:
  # container-job:
  #   runs-on: ubuntu-latest
  #   container: arm64/node:20.14.0-alpine
  #   steps:
  #       - run: node --version
  #       - run: npm --version
        
  test-job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      # - name: Prepare
      #   run: |
      #     sudo apt install binfmt-support qemu-user-static
          
      # - name: Setup Zig
      #   uses: goto-bus-stop/setup-zig@v2.2.0
      #   with:
      #     version: 0.13.0
      #     cache: true
      
      - name: Test
        run: |
          echo ROOTDIR=$(pwd)

