name: Test
run-name: "Test: ${{github.event.head_commit.message}}"
on:
  workflow_dispatch:
  push:
    paths: .github/workflows/test.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # - uses: actions/checkout@v4

      - name: find llvm-config
        run: |
          sudo apt update
          sudo apt search llmv-config
          sudo apt install llvm-config
          find /usr/bin/ -name "llvm-config*"    

