name: Test
run-name: "Test: ${{github.event.head_commit.message}}"
on:
  workflow_dispatch:
  push:
    paths: .github/workflows/test.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Debugging with tmate
      uses: mxschmitt/action-tmate@v3.18

              