name: Test
run-name: Build llvm ${{github.event.inputs.tag}}
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      ZIG_VERSION: 0.11.0

    steps:
      - name: test requirements
        run: |
          # https://code.visualstudio.com/docs/remote/linux
          # kernel >= 4.18, glibc >=2.28, libstdc++ >= 3.4.25, tar
          ldd --version
          find /usr -name libstdc++.so.6 | while IFS= read -r f; do
            strings "$f" | grep GLIBCXX
          done

