name: Test
run-name: "Test: ${{github.event.head_commit.message}}"
on:
  workflow_dispatch:
  push:
    paths: .github/workflows/test.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Prepare environment
        run: |
          sudo cat <<EOF > $HOME/.profile
          export CHARSET=\${CHARSET:-UTF-8}
          export LANG=\${LANG:-C.UTF-8}
          export LC_COLLATE=\${LC_COLLATE:-C}
          export TERM=xterm-256color
          export COLORTERM=truecolor
          EOF

          sudo apt update

          helix_vesion=24.07
          helix_url=https://github.com/helix-editor/helix/releases/download/${helix_vesion}/helix-${helix_vesion}-x86_64-linux.tar.xz
          curl -L ${helix_url} | xz -d | tar -C /opt -x
          ln -snf /opt/helix-${helix_vesion}-x86_64-linux/hx /usr/local/bin/hx
          hx --version

          dufs_version=0.41.0
          dufs_url=https://github.com/sigoden/dufs/releases/download/v0.41.0/dufs-v0.41.0-x86_64-unknown-linux-musl.tar.gz
          curl -L ${dufs_url} | xz -d | tar -C /usr/local/bin -x
          dufs --version

      - name: Debugging with tmate
        uses: mxschmitt/action-tmate@v3.18
